<ul>
    <li>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro, distinctio.</li>
    <li>Deleniti expedita sed adipisci velit, labore placeat atque quisquam enim!</li>
    <li>Perspiciatis vel voluptatibus sunt perferendis aliquam aspernatur consequatur, alias facilis.</li>
    <li>Quod explicabo nihil laborum recusandae obcaecati at ab delectus doloribus!</li>
    <li>Repellat itaque non facere soluta libero et molestias harum ex!</li>
</ul>