<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $title ?></title>
    <link rel="stylesheet" href="css/main.css">
</head>

<body>
    <nav>
        <a href="index.php">Home</a>
        <a href="presentation.php">Présentation</a>
        <a href="produits.php">Produits</a>
        <a href="equipe.php">Equipe</a>
        <a href="equipe.php?display=direction">Direction</a>
        <a href="contacts.php">Contacts</a>
    </nav>

    <main>
        <?php include('views/' . $view . '.phtml') ?>
    </main>
</body>

</html>